services:
  db:
    restart: unless-stopped
    image: postgres:17
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: broadway_on_demand
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  redis:
    restart: unless-stopped
    image: redis:8
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  docker:
    restart: unless-stopped
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_data:/var/jenkins_home
    ports:
      - "2376:2376"
    command:
      - --storage-driver=overlay2

  jenkins:
    restart: unless-stopped
    image: ghcr.io/cs341-illinois/jenkins:latest
    ports:
      - "127.0.0.1:8080:8080"
    extra_hosts:
      - "localhost:172.17.0.1"
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins_data:/var/jenkins_home
    depends_on:
      - docker
    healthcheck:
      test: curl --fail http://localhost:8080/jenkins/login || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

volumes:
  pg_data:
  jenkins_data:
  jenkins-docker-certs:
